env:
  database: "off"
  nginx_worker_processes: "1"
  proxy_listen: "0.0.0.0:8000, 0.0.0.0:8443 ssl http2"

ingressController:
  enabled: true
  installCRDs: true

proxy:
  enabled: true
  type: NodePort
  http:
    enabled: true
    servicePort: 8000
    nodePort: 32080
  tls:
    enabled: true
    servicePort: 8443
    nodePort: 32443

admin:
  enabled: false

manager:
  enabled: false