apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: balance-cert
  namespace: balance
spec:
  secretName: balance-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - balance.local